name: wsisa
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # 指定 Python 版本
  - python=3.9

  # 基础数值库
  - numpy
  - scipy
  - scikit-learn
  - pandas

  # PCA / 聚类需要的库
  - scikit-learn

  # Faiss（CPU 版）
  - faiss-cpu

  # 图像处理
  - pillow       # PIL
  - opencv       # cv2

  # 进度条
  - tqdm

  # 其它常用实用库
  - joblib
  - pip
  - mkl        # Intel Math Kernel Library
  - mkl-service

  # 如果你还有部分包想从 pip 安装，放在下面
  - pip:
    # - some-pypi-package==x.y.z